name: Compile
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: perkinslr/SolastaReferenceAssemblies
        ssh-key: ${{ secrets.REF_DEPLOY_KEY }}
        path: SolastaReferenceAssemblies
    - name: prebuild
      run: |
        mv /home/runner/work/SolastaUnfinishedBusiness/SolastaUnfinishedBusiness/SolastaReferenceAssemblies /home/runner/work
    - uses: actions/checkout@v3
      with:
        clean: false
    - name: restore
      run: |
        pwd
        ls -l
        ls /home/runner/work/SolastaReferenceAssemblies -l
        ls -l lib
        SolastaInstallDir=/home/runner/work/SolastaReferenceAssemblies SolutionDir=$PWD dotnet restore SolastaUnfinishedBusiness.sln
    - name: clean
      run: |
        SolastaInstallDir=/home/runner/work/SolastaReferenceAssemblies SolutionDir=$PWD dotnet clean SolastaUnfinishedBusiness.sln  
    - name: build
      run: |
        SolastaInstallDir=/home/runner/work/SolastaReferenceAssemblies SolutionDir=$PWD dotnet build SolastaUnfinishedBusiness.sln
    - uses: actions/upload-artifact@v4
      with:
        name: UnfinishedBusiness
        path: SolastaReferenceAssemblies/Mods
        
